apps/search/google/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('google', views.result)
]

apps/search/urls.py
from django.urls import path, include
from .views import Search
from .views import logout_user

app_name = 'search'

urlpatterns = [
    path('', Search.as_view(), name='search'),
    path('logout/', logout_user, name='logout'),
    path('search/', include('apps.search.google.urls'))
]

bob/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('apps.search.urls')),
    path('', include('apps.search.urls', namespace='search'))
]

search/google/urls.py
from django.urls import path
from search.google import views

urlpatterns = [
    path('google', views.result)
]

apps/search/google/models.py
from django.db import models

# Create your models here.

apps/search/google/views.py
import json
from dataclasses import dataclass, field, asdict
from typing import List

from django.http import JsonResponse

from apps.search.google.google_custom_search_engine import GoogleCSE


@dataclass
class Response:
    error: bool = False
    message: str = ''
    results: List[GoogleCSE.GoogleResult] = field(default_factory=list)


def result(request):
    """Get google-search results via Google Custom Engine Search."""
    # Get search term from request body
    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)
    search_term = body['search_term']

    # Get google search results
    google_search = GoogleCSE()
    google_response = Response()
    try:
        google_response.results = google_search.search_on_multiply_pages(search_term=search_term)
    except Exception as e:
        google_response.error = True
        google_response.message = e
        return JsonResponse(asdict(google_response), safe=False)
    return JsonResponse(asdict(google_response), safe=False)

apps/search/views.py
from django.views import View
from django.contrib.auth import logout
from django.shortcuts import redirect, render


class Search(View):

    template_name = 'search/search.html'

    def get(self, request):

        return render(request, self.template_name)

    def post(self, request):

        return self.get(request)


def logout_user(request):
    logout(request)
    return redirect('search:login')

search/google/views.py
import json

from django.http import HttpResponse
from search.google import google_custom_search_engine


def result(request):
    """Get google-search results via Google Custom Engine Search."""
    # Get search term from request body
    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)
    search_term = body['search_term']

    # Get google search results
    google_search = google_custom_search_engine.GoogleCSE()
    try:
        results = google_search.search_on_multiply_pages(search_term=search_term)
    except Exception as e:
        return HttpResponse(e)
    return HttpResponse(results, content_type='application/json')

apps/search/templates/search/base.html
{% extends 'search/core.html' %}
{% load static %}
{% block body %}

<nav class="topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white"
     id="sidenavAccordion">
    <!-- Sidenav Toggle Button-->
    <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 me-2 ms-lg-2 me-lg-0" id="sidebarToggle">
        <i data-feather="menu"></i>
    </button>
    <!-- Navbar Brand-->
    <!-- * * Tip * * You can use text or an image for your navbar brand.-->
    <!-- * * * * * * When using an image, we recommend the SVG format.-->
    <!-- * * * * * * Dimensions: Maximum height: 32px, maximum width: 240px-->
    <a class="navbar-brand pe-3 ps-4 ps-lg-2" href="/">Bob Search</a>
    <ul class="navbar-nav align-items-center ms-auto">
        {% if user.is_superuser %}
        <li class="nav-item dropdown no-caret me-3 me-lg-4">
            <a class="nav-link" href="{% url 'admin:index' %}">
                <div class="nav-link-icon">
                    <i data-feather="settings"></i>
                </div>
            </a>
        </li>
        {% endif %}
        <li class="nav-item dropdown no-caret me-3 me-lg-4">
            <a class="nav-link" href="{% url 'search:logout' %}">
                <div class="nav-link-icon">
                    <i data-feather="log-out"></i>
                </div>
            </a>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sidenav shadow-right sidenav-light">
            <div class="sidenav-menu">
                <div class="nav accordion" id="accordionSidenav">
                    <!-- Sidenav Menu Heading (Account)-->
                    <!-- * * Note: * * Visible only on and above the sm breakpoint-->
                    <div class="sidenav-menu-heading d-sm-none">Account</div>
                    <!-- Sidenav Link (Alerts)-->
                    <!-- * * Note: * * Visible only on and above the sm breakpoint-->
                    <a class="nav-link d-sm-none" href="#!">
                        <div class="nav-link-icon">
                            <i data-feather="bell"></i>
                        </div>
                        Alerts
                        <span class="badge bg-warning-soft text-warning ms-auto">4 New!</span>
                    </a>
                    <!-- Sidenav Link (Messages)-->
                    <!-- * * Note: * * Visible only on and above the sm breakpoint-->
                    <a class="nav-link d-sm-none" href="#!">
                        <div class="nav-link-icon">
                            <i data-feather="mail"></i>
                        </div>
                        Messages
                        <span class="badge bg-success-soft text-success ms-auto">2 New!</span>
                    </a>

                    <div class="sidenav-menu-heading">Core</div>
                    <a class="nav-link" href="/">
                        <div class="nav-link-icon">
                            <i data-feather="airplay"></i>
                        </div>
                        Search
                    </a>

                    <!--                    <div class="sidenav-menu-heading">Statistic</div>-->
                    <!--                    <a class="nav-link" href="/dashboard">-->
                    <!--                        <div class="nav-link-icon">-->
                    <!--                            <i data-feather="activity"></i>-->
                    <!--                        </div>-->
                    <!--                        Dashboard-->
                    <!--                    </a>-->


                    <!--                    <div class="sidenav-menu-heading">Support</div>-->

                    <!--                    <a class="nav-link" href="/help">-->
                    <!--                        <div class="nav-link-icon">-->
                    <!--                            <i data-feather="help-circle"></i>-->
                    <!--                        </div>-->
                    <!--                        Help-->
                    <!--                    </a>-->


                </div>
            </div>
            <!-- Sidenav Footer-->
            <div class="sidenav-footer">
                <div class="sidenav-footer-content">
                    <div class="sidenav-footer-subtitle">Logged in as:</div>
                    <div class="sidenav-footer-title">{% if user.is_authenticated %}
                        {{ user.get_username }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            {% block content %}
            {% endblock %}
        </main>

    </div>
</div>

{% endblock %}

apps/search/templates/search/core.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    <title>VPN Manager</title>


    <link href="{% static 'search/img/favicon.svg' %}" rel="icon" type="image/x-icon">


    <!--CSS libs-->
    <link href="{% static 'search/libs/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'search/libs/jquery-ui/jquery-ui.css' %}" rel="stylesheet">

    <link href="{% static 'search/libs/chart.js/Chart.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'search/libs/dataTables/dataTables.bootstrap5.css' %}" rel="stylesheet" type="text/css"/>

    <link href="{% static 'search/libs/bootstrap-datepicker/bootstrap-datepicker.standalone.css' %}" rel="stylesheet"
          type="text/css"/>


    <link href="{% static 'search/libs/bootstrap4-toggle/bootstrap4-toggle.min.css' %}" rel="stylesheet"
          type="text/css"/>
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">


    <!-- Custom CSS-->
    <link href="{% static 'search/css/styles.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'search/css/css.css' %}" rel="stylesheet" type="text/css"/>


    <!--JavaScript libs-->
    <script src="{% static 'search/libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'search/libs/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'search/libs/moment.js/moment.min.js' %}"></script>
    <script src="{% static 'search/libs/litepicker/bundle.js' %}"></script>
    <script src="{% static 'search/libs/bootstrap4-toggle/bootstrap4-toggle.min.js' %}"></script>

    <!--    <script src="{% static 'search/libs/daterangepicker/daterangepicker.js' %}"></script>-->
    <!--    <script src="{% static 'search/libs/bootstrap-datepicker/bootstrap-datepicker.js' %}"></script>-->

    <script src="{% static 'search/libs/font-awesome/js/all.js' %}"></script>
    <script src="{% static 'search/libs/feather-icons/js/feather.js' %}"></script>
    <script src="{% static 'search/libs/bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'search/libs/chart.js/Chart.js' %}"></script>
    <!--    <script src="{% static 'search/libs/simple-datatables/datatable.js' %}"></script>-->
    <script src="{% static 'search/libs/dataTables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'search/libs/dataTables/dataTables.bootstrap5.js' %}"></script>
    <script src="{% static 'search/libs/dataTables/dataTables.responsive.min.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>

    <!-- Custom scripts-->
    <script src="{% static 'search/js/scripts.js' %}"></script>


</head>

<body class="nav-fixed">
{% block body %}
{% endblock %}
</body>


</html>

apps/search/templates/search/search.html
{% extends 'search/base.html' %}
{% load static %}
{% block content %}

<header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
    <div class="container-xl px-4">
        <div class="page-header-content pt-4">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto mt-4">
                    <h1 class="page-header-title">
                        <div class="page-header-icon">
                            <div class="nav-link-icon">
                                <i data-feather="airplay"></i>
                            </div>
                        </div>
                        Search
                    </h1>
                    <div class="page-header-subtitle">Search panel</div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container-xl px-4 mt-n10">
    <div class="row">

        <div class="input-group input-group-lg col-xl-10 mb-10">
            <div class="input-group-text">
                <img src="{% static 'search/img/google.ico' %}">
            </div>
            <input class="form-control" id="search-input" placeholder="Search" required="" type="text">
            <button class="btn btn-primary" id="button-search" type="button">
                <i data-feather="search"></i>
            </button>
        </div>
    </div>

    <div class="row">
        <div class="card mb-4">
            <div class="card-header">Extended DataTables</div>
            <div class="card-body">
                <table id="datatablesSimple">
                </table>
                <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                    <div></div>
                    <div>
                        <button class="btn btn-primary float-left" type="button" data-bs-toggle="modal"
                                data-bs-target="#modal">
                            Обработать
                        </button>
                    </div>

                </div>


            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Внимание</h5>
                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Подтверждаете обработку данных ?
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Отменить</button>
                <button class="btn btn-primary" type="button">Подтвердить</button>
            </div>
        </div>
    </div>
</div>

<div id="error-modal">

</div>

<script src="{% static 'search/js/search.js' %}"></script>

{% endblock %}